server:
  port: 8000



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abode
    username: plutus
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.morosa.abode.controller: INFO
    com.morosa.abode.utils: DEBUG
  file:
    name: abode.log
  config: classpath:logback-spring.xml

secret:
  cloudinary:
    cloud_name: your_cloud_name
    api_key: your_api_key
    api_secret: your_api_secret
